name: âœ… Build

on: pull_request

jobs:
  Build:
    env:
      rdns: dev.yuua
      name: JourneyLib
      platform: actions
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›°ï¸ Start Notification
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          webhook: ${{ secrets.DISCORD_NOTIFY }}
          title: "Started: â˜• ${{ env.name }} Test Build"
          description: "[${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          color: 0xeaa6e9
      - name: ğŸ“» Setup JDK16
        uses: actions/setup-java@v3.0.0
        with:
          distribution: "zulu"
          java-version: "16"
      - name: ğŸ˜ Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: ğŸ“¦ Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: project
      - name: âŒ› Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ğŸ˜ Gradle Build
        run: |
          cd project
          gradle build
      - name: ğŸ›°ï¸ End Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_NOTIFY }}
          title: "â˜• ${{ env.name }} Test Build"
          color: 0xeaa6e9
