name: ğŸ—ƒï¸ Publish

on:
  push:
    branches:
      - main
      - dev

jobs:
  Publish:
    env:
      emoji: â˜•
      rdns: dev.yuua
      name: JourneyLib
      platform: actions
      jdk: 16
      gradle_cmd: build
      ref_main: "main"
      ref_dev: "dev"
    runs-on: ubuntu-latest
    steps:
      - name: âŒ¨ï¸ Project Name
        id: name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.name }}
      - name: ğŸ‘‰ Release Version
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          default_bump: "minor"
          custom_release_rules: "breaking:major:ğŸ’£ Breaking Changes,feat:minor:âœ¨ Features,fix:patch:ğŸ’£ Bug Fixes,docs:patch:ğŸ“° Docs,chore:patch:ğŸ¨ Chore,pref:patch:ğŸˆ Performance improvements,refactor:patch:ğŸ§¹ Refactoring,build:patch:ğŸ” Build,ci:patch:ğŸ” CI,revert:patch:âª Revert,style:patch:ğŸ§¹ Style,test:patch:ğŸ‘€ Test"
      - name: ğŸ›°ï¸ Start Notification
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          webhook: ${{ secrets.DISCORD_NOTIFY }}
          title: "Started: ${{ env.emoji }} ${{ env.name }} v${{ steps.version.outputs.new_version }}"
          description: "[${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          color: 0xeaa6e9
      - name: ğŸ“» Setup JDK16
        uses: actions/setup-java@v3.0.0
        with:
          distribution: "zulu"
          java-version: ${{ env.jdk }}
      - name: ğŸ˜ Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: ğŸ“¦ Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: project
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: yuuahp/repo.yuua.dev
          token: ${{ secrets.ActionsToken }}
          path: repository
      - name: âŒ› Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ğŸ—ƒï¸ Deploy
        env:
          project_version: ${{ steps.version.outputs.new_version }}
          project_user: ${{ secrets.user }}
          project_token: ${{ secrets.token }}
        run: |
          echo $project_version
          mv ./repository/docs/ ./project/artifacts/
          cd ./project
          gradle publish
          mv -uf ./artifacts/ ../repository/docs/
          cd ../repository
          git config --global user.name "AutoBuilder"
          git config --global user.email yuuahp@icloud.com
          git add *
          git commit -m "add: ${{ env.name }} v${{ env.project_version }} ${{ env.emoji }}"
          git push
      - name: ğŸ—ƒï¸ Publish Release (main)
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        if: github.ref_name == env.ref_main
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: "v${{ env.project_version }}"
      - name: ğŸ—ƒï¸ Publish Release (dev)
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        if: github.ref_name == env.ref_dev
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          tag_name: "v${{ env.project_version }}"
      - name: ğŸ›°ï¸ End Notification
        uses: sarisia/actions-status-discord@v1
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        with:
          webhook: ${{ secrets.DISCORD_NOTIFY }}
          title: "${{ env.emoji }} ${{ env.name }} v${{ env.project_version }}"
          description: "`implementation(\"${{ env.rdns }}:${{ steps.name.outputs.lowercase }}:${{ env.project_version }}\")`"
          color: 0xeaa6e9
