name: ğŸ—ƒï¸ Transmit

on:
  push:
    branches:
      - main

jobs:
  Transmit:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘‰ Release Version
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          default_bump: "minor"
          custom_release_rules: "feat:minor:âœ¨ Features,fix:patch:ğŸ’£ Bug Fixes,docs:patch:ğŸ“° Docs,chore:patch:ğŸ¨ Chore,pref:patch:ğŸˆ Performance improvements,refactor:patch:ğŸ§¹ Refactoring,build:patch:ğŸ” Build,ci:patch:ğŸ” CI,revert:patch:âª Revert,style:patch:ğŸ§¹ Style,test:patch:ğŸ‘€ Test"
      - name: ğŸ“» SetUp JDK16
        uses: actions/setup-java@v2.5.0
        with:
          distribution: "zulu"
          java-version: "16"
      - name: ğŸ˜ Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: ğŸ“¦ Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: project
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: yuuahp/repo.yuua.dev
          token: ${{ secrets.ActionsToken }}
          path: repository
      - name: âŒ› Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ğŸ—ƒï¸ Publish
        env:
          journeylib_version: ${{ steps.version.outputs.new_version }}
        run: |
          echo $journeylib_version
          mv ./repository/docs/ ./project/artifacts/
          cd ./project
          gradle publish
          mv -uf ./artifacts/ ../repository/docs/
          cd ../repository
          git config --global user.name "AutoBuilder"
          git config --global user.email yuuahp@icloud.com
          git add *
          git commit -m "add: index(${{ github.repository }})"
          git push